### ISSUE TITLE
metalsmith-sitemap dependency

### ISSUE THREAD

**Issue by millette** [eddywashere/generator-ironsmith#2]
After installing the generator, I launched yo ironsmith but it failed with the metalsmith-sitemap dependency. I updated the package.json to use 0.0.10 instead of a dev version of metalsmith-sitemap and that seemed to work fine.

**Comment by eddywashere** [comment]
Thanks for the report! I'll get that updated and close this issue when it's merged.

**Comment by eddywashere** [comment]
@millette just published 1.0.10 with the fix https://github.com/eddywashere/generator-ironsmith/commit/20d9cc5e2253a0b05bbecfab65c2ae9b35bec956

Thanks again for filing an issue!

**Comment by millette** [comment]
Great, thanks for the quick response.
